---
abstract: 'a simple script to remove spaces from filenames or file contents, but also a tribute to old school robust bioinformatics tools'
author:
  - 'Andrea Telatin <proch@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Cavaspazi
provides:
  Acme::Cavaspazi:
    file: lib/Acme/Cavaspazi.pm
    version: v0.1.0
requires:
  Carp: '1.2'
  FindBin: '1.3'
  JSON::PP: '0'
  PerlIO::encoding: '0'
  Pod::Usage: '0'
  perl: '5.012'
resources:
  repository: https://github.com/telatin/FASTX-Reader
version: 0.1.0
x_serialization_backend: 'YAML::Tiny version 1.70'
