on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ '5.34', '5.24', '5.18' ]
    container:
      image: perl:${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev libpng-dev
      - name: Install Dzil
        run: |
          # Install using cpanm
          cpanm -qn Dist::Zilla

      - name: Run build script
        run: |
          dzil authordeps --missing | cpanm -qn
          dzil listdeps --author --missing  | cpanm -qn
          dzil test --author --verbose


